opendatahub-io/llama-stack-demos

mcp-servers/llamastack/README.md
mcp-servers/llamastack/custom_prompts.py
mcp-servers/llamastack/mcp_server.py
mcp-servers/llamastack/openapi_parser.py
mcp-servers/llamastack/requirements.txt

The PR adds initial llamastack server files to be built on.

Add initial llamastack server files

---

Makefile
app/src/build/Containerfile
app/src/streamlit_app.py
kubernetes/streamlit-client/deployment.yaml
kubernetes/streamlit-client/route.yaml
kubernetes/streamlit-client/service.yaml

Adding a very simple and intentionally non-functional UI while we work on adding the authentication layer infront of the UI.

add simple streamlit ui

---

app/src/streamlit_app.py

Requested changes that got missed in #24.

small updates to streamlit_app that were missed in #24

---

app/src/build/Containerfile
kubernetes/streamlit-client/deployment.yaml

update streamlit_app deployment and Containerfile to updated UI.

update streamlit_app deployment and Containerfile

---

mcp-servers/openshift/Containerfile
mcp-servers/openshift/README.md
mcp-servers/openshift/deployment.yaml

Add openshift MCP server

---

mcp-servers/llamastack/Containerfile
mcp-servers/llamastack/README.md
mcp-servers/llamastack/deployment.yaml
mcp-servers/llamastack/mcp_server.py
mcp-servers/llamastack/openapi.json

Summary:
Temporary adjustment to llamastack/mcp_server.py to use openapi.json file locally while remote fix is underway
Container image and deployment file for deploying on openshift
A minimal README.md for how to use the script

llamastack-mcp-server

---

README.md

fix of readme - incorrect command

---

.github/workflows/mcp-builds.yaml

Limit the MCP runs to only the mcp-servers direcotry

Limit the build runs to mcp dir

---

kubernetes/llama-stack/configmap.yaml
kubernetes/llama-stack/deployment.yaml
kubernetes/llama-stack/template.yaml

update llama-stack manifests

---

README.md
pyproject.toml
uv.lock

Added some basic package management

add pyproject, uv.lock and updated instructions

---

kubernetes/mcp-servers/ansible-mcp/ansible-deployment.yaml
kubernetes/mcp-servers/ansible-mcp/ansible-service.yaml
kubernetes/mcp-servers/ansible-mcp/kustomization.yaml

Updated deployment files for ansible mcp server

Deployment update

---

kubernetes/observability/README.md
kubernetes/observability/run-configuration.md
kubernetes/observability/tempo/kustomization.yaml
kubernetes/observability/tempo/minio-user-creds.yaml

small update to the observability/tempo files.
@cooktheryan ptal, ty!

update tempo files

---

kubernetes/observability/grafana/vllm-dashboard/vllm-dashboard.yaml
kubernetes/observability/grafana/vllm-dashboard/vllm-grafana-openshift.json

Adds the vLLM Grafana dashboard

Add vLLM Grafana dashboard

---

demos/rag_agentic/notebooks/Level1_foundational_RAG.ipynb

Added missing imports to `Level 1: Foundational RAG` notebook

fix: Missing imports

---

local_setup_guide.md

@amfred, @anyuzoey, @hemajv, @Shreyanand, @suppathak, @AIMikav, @kevincogan I added you all as co-authors here since I'm mainly just moving https://github.com/redhat-et/agent-frameworks/blob/main/prototype/frameworks/llamastack/README.md into this repo and it looks like you all contributed there. Let me know if I've missed anyone 😄

move setup guide from agent-frameworks to this repo

---

tests/results/metrics.csv
tests/test_mcp_servers.py

Update testing script

---

demos/rag_agentic/README.md

provide draft readme for demo/rag_agentic folder. Addree issue: https://github.com/opendatahub-io/llama-stack-demos/issues/83

docs: update rag_agentic README with some structure intro

---

mcp-servers/slack/Containerfile
mcp-servers/slack/README.md
mcp-servers/slack/secret.yaml

Adding WIP pull request to reflect my attempt to get slack MCP running on OpenShift. Currently stuck on getting it deployed correctly.

Added Slack MCP Server

---

kubernetes/mcp-servers/slack-mcp/kustomization.yaml
kubernetes/mcp-servers/slack-mcp/slack-deployment.yaml
kubernetes/mcp-servers/slack-mcp/slack-secret.yaml
kubernetes/mcp-servers/slack-mcp/slack-service.yaml

Add the deployment files for Slack MCP server

add slack mcp server

---

kubernetes/streamlit-client/deployment.yaml

updated streamlit-client deployment to use redhat-et org

---

README.md
kubernetes/kustomization.yaml
kubernetes/llama-stack/configmap.yaml

only enabled required MCP servers

---

kubernetes/README.md
kubernetes/llama-serve/README.md
kubernetes/llama-stack/README.md
kubernetes/mcp-servers/README.md
kubernetes/safety-model/README.md
kubernetes/streamlit-client/README.md

Addresses https://github.com/opendatahub-io/llama-stack-demos/issues/139

Update READMEs for /kubernetes folder

---

demos/rag_agentic/README.md

Update level4 notebook with demo recording link of slack mcp server: https://youtu.be/aaxclldaVWw

Add demo recording link to level4 notebook

---

kubernetes/llama-stack/deployment.yaml

Modify the YAML to support the usage of RHOAI model serving

using rhoai

---

.github/workflows/llama-stack-build.yaml

need to test with actions for efficency

testing on pr

---

kubernetes/kustomize/overlay/dev/kustomization.yaml
kubernetes/kustomize/overlay/dev/run-config-patch.yaml
kubernetes/llama-stack/run.yaml

@hemajv I had to swap this in. There was an error in the existing configuration

broken configmap

---

kubernetes/llama-stack/deployment.yaml

bump version to code freeze version

bump to summit version

---

demos/rag_agentic/README.md
demos/rag_agentic/notebooks/Level4_agentic_RAG.ipynb
demos/rag_agentic/notebooks/Level5_agentic_and_mcp.ipynb
demos/rag_agentic/notebooks/Level6_agentic_MCP_and_RAG.ipynb

Updating the README and notebooks to match the updated notebook names
1. The README now includes all notebooks in its description (i.e. the new level 3 notebook still to be merged)
2. It includes the Narrative of the Notebooks
3. All notebooks updated with updated name and links to the updated notebook names
Links checked, via clicking on links
- [x ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ x] The developer has manually tested the changes and verified that the changes work

README and notebook naming+links updates

---

kubernetes/notebooks/lab-bench.yaml

required files

---

README.md

Update README with repository structure 

---

demos/rag_agentic/notebooks/Level6_agentic_MCP_and_RAG.ipynb

Updating the Markdown to say Level 6 rather than Level 5
Updating the Markdown to say Level 6 rather than Level 5
N/A
- [ x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ x] The developer has manually tested the changes and verified that the changes work

Level6 rather than Level5

---

kubernetes/llama-stack/deployment.yaml
kubernetes/llama-stack/run.yaml

remove otel

---

demos/rag_agentic/notebooks/Level5_agentic_and_mcp.ipynb
demos/rag_agentic/notebooks/Level6_agentic_MCP_and_RAG.ipynb

Removing unused prompts in notebook 5 & 6 
Updated the Markdowns

Remove unused prompts from NB 5&6

---

distribution/build.yaml

Was removed from llama-stack in
https://github.com/meta-llama/llama-stack/pull/2087

chore: rm inline::code-interpreter

---

demos/rag_agentic/notebooks/Level3_advance_agentic_with_Prompt_Chaining_ReAct.ipynb

text edits to level3 notebook

---

demos/rag_agentic/notebooks/Level4_agentic_RAG.ipynb

Some minor text edits for notebook 4

text edits to level4 notebook

---

demos/rag_agentic/notebooks/Level5_agentic_and_mcp.ipynb

Some text updated to notebook 5

text edits to level5 notebook

---

demos/rag_agentic/README.md
demos/rag_agentic/notebooks/Level1_simple_RAG.ipynb
demos/rag_agentic/notebooks/Level2_simple_agent_with_websearch.ipynb
demos/rag_agentic/notebooks/Level3_advanced_agent_with_Prompt_Chaining_and_ReAct.ipynb
demos/rag_agentic/notebooks/Level4_RAG_agent.ipynb
demos/rag_agentic/notebooks/Level5_agents_and_mcp.ipynb
demos/rag_agentic/notebooks/Level6_agents_MCP_and_RAG.ipynb

Mostly just changed the word "agentic" to "agent"

renamed notebooks and updated links in rag_agentic demo

---

demos/rag_agentic/src/utils.py

This PR fixes a minor bug in step_printer where an invalid JSON object is received.

Fixing a small bug in step_printer

---

demos/rag_agentic/notebooks/Level5_agents_and_mcp.ipynb

Update Level5 notebook to include an additional user prompt for deploying a simulated erroneous `slack-test` pod

Update level5 notebook to include pod creation user prompt

---

demos/rag_agentic/notebooks/Level6_agents_MCP_and_RAG.ipynb

Update and clean up level6

---

kubernetes/llama-stack/run.yaml

Fix slack mcp server in run.yaml

---

demos/rag_eval/Agentic_RAG_with_reference_eval.ipynb

Updated the links to the other notebooks with the correct links
Links weren't updated since being moved to a new dir.
Udpated the links
Clicked links. Links worked.

[Fix] Broken links in Agentic_RAG_with_reference_eval notebook 4.5

---

distribution/providers.d/remote/eval/lmeval.yaml

Upgrade LM-Eval to fix wrong import path error:
```
from src.llama_stack_provider_lmeval.errors import LMEvalConfigError
ModuleNotFoundError: No module named 'src'
```

fix: update LM-Eval version

---

.github/workflows/llama-stack-build.yaml
demos/rag_agentic/notebooks/requirements.txt
distribution/build-external-provider.yaml
distribution/build.yaml
pyproject.toml
uv.lock

working on version bump and support for external providers

version bump and facilitate external

---

demos/a2a_llama_stack/README.md
demos/a2a_llama_stack/requirements.txt

Made minor changes to A2A llama_stack agent.
* Dependency issue under `demos/a2a_llama_stack/requirements.txt`
* Minor change on README 
I was running an E2E with Kevin's original demo on A2A/LlamaStack and found a few problems and made some improvements accordingly.
I have checked that it will not result in MR with Kevin's current PR: https://github.com/opendatahub-io/llama-stack-demos/pull/246.

chore: minor A2A readme and requirements.txt update

---

demos/rag_agentic/notebooks/requirements.txt

Add python-dotenv to rag_agentic/requirements.txt
Without this package the rag_agentic demos fail to import: "from dotenv import load_dotenv"
Tried the notebook in the demo env
I ran the "Level 0: Getting Started with Llama Stack" in the demo env and got an error

chore: Add python-dotenv to requirements.txt

---

demos/a2a_llama_stack/notebooks/A2A_Agentic_RAG.ipynb

Changed Level4_RAG_agent.ipynb  and Setup guide  hyperlink
Redirects Level4_RAG_agent.ipynb and Setup guide to the right location
When link was clicked it would redirect to uncreated location

chore: minor change to hyperlinks in notebook

---

demos/rag_agentic/notebooks/Level0_getting_started_with_Llama_Stack.ipynb
demos/rag_agentic/notebooks/requirements.txt
kubernetes/notebooks/lab-bench.yaml

the dotenv file was giving us fits. This will by pass that problem.

Fixes to allow level 0 to run
