kubernetes/llama-stack/configmap.yaml
kubernetes/llama-stack/deployment.yaml
kubernetes/llama-stack/route.yaml
kubernetes/llama-stack/service.yaml

These are missing if we use this repo to deploy we'll need the svc & route. Also updates to 0.1.8 if that's what we decide on.

update ls manifests to 0.1.8, add svc,route

---

app/src/streamlit_app.py

Updated the streamlit client so that it will: 
* Use a llama stack agent for text inference and tool use. 
* Users can quickly swap between all llms available on their llama stack server.
* Users can select the MCP servers they wish to use that are available on their servers.

Update streamlit client to use llama stack server

---

mcp-servers/ansible/ansible_tool_queries.json

This PR adds a JSON file containing a curated set of queries targeting read-only and safe tools in the Ansible MCP server.
Model: `meta-llama/Llama-3.2-3B-Instruct` demonstrated the most reliable performance in identifying and invoking the correct tools.
✅ Tools Covered
The following tools were successfully invoked in this set:
- list_recent_jobs
- list_inventories
- get_inventory
- list_job_templates

Add JSON file listing verified working queries for Ansible MCP tools

---

mcp-servers/openshift/queries_openshift.json

This PR adds a JSON file containing a set of example queries for the OpenShift MCP server.
**Model:** `ibm-granite/granite-3.2-8b-instruct` currently seems to be performing the best in identifying and invoking the correct tools.
**Tools Covered**
The following tools were successfully invoked in this set:
- pods_list_in_namespace
- pods_delete
- pods_log
- pods_run
- events_list
**Note:** I had to also set the `sampling_params: {"max_tokens":1024}` when defining the `Agent` config in order to get successful output responses

Add example queries for OpenShift MCP server

---

kubernetes/README.md
kubernetes/llama-stack/configmap.yaml
kubernetes/llama-stack/deployment.yaml

This PR introduces changes to update the llamastack deployment with:
- New llamastack remote-vllm quay image with **in-line milvus available**: `quay.io/redhat-et/remote-vllm-milvus:0.1.9`
- `run.yaml` updated in the configmap to include milvus

Update llamastack to use in-line milvus

---

app/src/streamlit_app.py

Redesigned layout for the Active Tools section in the Streamlit app.
Instead of showing tools in a flat JSON list, tools are now:
- Grouped under their corresponding MCP servers using st.expander
- Displayed with numbered labels and fully qualified names like mcp::openshift:pods_list
This improves readability and makes it easier to trace tool provenance when multiple MCP servers are selected.
- Tested locally using python -m streamlit run streamlit_app.py
- Environment: macOS, Python 3.11
- Selected multiple MCP servers from the sidebar.
- Verified that tools are displayed correctly under each server

Redesigning active tool list display

---

kubernetes/observability/guidellm/Containerfile
kubernetes/observability/guidellm/README.md
kubernetes/observability/guidellm/accessor-pod.yaml
kubernetes/observability/guidellm/guidellm-job.yaml
kubernetes/observability/guidellm/pvc.yaml
kubernetes/observability/guidellm/retriever-job.yaml

This adds an example for how to run [guidellm](https://github.com/neuralmagic/guidellm/blob/main/README.md) and extract the report to your local environment.
@cooktheryan @MichaelClifford ptal, ty!

add guidellm example

---

kubernetes/llama-stack/configmap.yaml
kubernetes/llama-stack/deployment.yaml

```
llama-stack-client toolgroups list
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ identifier                ┃ provider_id            ┃ args ┃ mcp_endpoint                                                                                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ builtin::code_interpreter │ code-interpreter       │ None │ None                                                                                            │
│ builtin::rag              │ rag-runtime            │ None │ None …
```

use configmap to define mcp servers

---

demos/rag_agentic/notebooks/Level4_agentic_and_mcp.ipynb

Version bump to work with `v0.2.2`. Everything worked out of the box, just needed to update docs.

updated references to ls 0.2.2 for ocp version draft email

---

demos/rag_agentic/notebooks/extras/mcp_toolgroup_management.ipynb

Adds a notebook showing how to register, unregister, and list MCP toolgroups using llama-stack-client. Useful for managing tool integrations in LlamaStack.

Added notebook for managing mcp servers through llamastack

---

.github/workflows/llama-stack-build.yaml
distribution/README.md
distribution/build.yaml
distribution/providers.d/remote/eval/lmeval.yaml
pyproject.toml
uv.lock

This commit contains the necessary artifact to build our llama-stack distribution for doing demos.
Opening as a draft since https://github.com/trustyai-explainability/llama-stack-provider-lmeval/issues/1 needs to be resolved for the build to succeed.

feat: add llama-stack distribution artifact

---

kubernetes/kustomize/overlay/demo/kustomization.yaml
kubernetes/kustomize/overlay/demo/remove-tavily-env.yaml

We won't be able to directly provide the demo environment a key so we need to remove this once kustomize generates the files

removal of tavily for demo env

---

.env.example
demos/rag_agentic/notebooks/Level0_getting_started_with_Llama_Stack.ipynb
demos/rag_agentic/notebooks/Level1_foundational_RAG.ipynb
demos/rag_agentic/notebooks/Level2_simple_agentic_with_websearch.ipynb
demos/rag_agentic/notebooks/requirements.txt

The majority of the changes in this PR are edits to the markdown text and instructions in notebooks 0, 1, and 2 in the `rag_agentic` demo. 
Other Changes include:
* Added default values to the `.env.example` file.
* Removed the use of `REMOTE` and `LOCAL_SERVER_PORT` env variables in favor of simply having the Llama Stack server always point to `REMOTE_BASE_URL` for each notebook. This should make things simpler for users.  
* Added a `requirements.txt` file to the `notebooks/` directory and changed the `! pip install ...` cell to use `requirements.txt` instead of specifying specific package names. This should make this demo more maintainable over time.

Tutorial review for Notebooks 0, 1 and 2

---

distribution/build.yaml

build errors are occurring https://github.com/opendatahub-io/llama-stack-demos/actions/runs/14914782139 
@dmartinol can you look into this during your morning?

removal of eval

---

demos/rag_agentic/notebooks/Level2_simple_agentic_with_websearch.ipynb
demos/rag_agentic/notebooks/Level3_advance_agentic_with_Prompt_Chaining_ReAct.ipynb

Level2 and Level3 notebooks are using the old version of importing the `Agent` module, updating it to be consistent with the other notebooks

update level2 and level3 with correct imports

---

demos/rag_agentic/notebooks/Level5_agents_and_mcp.ipynb

Fix: Update MCP Server Installation Paths and Tavily API Link
This pull request updates several file paths and a URL to ensure they are accurate and up-to-date. Specifically:
-   Corrected the file paths for OpenShift and Slack MCP server installation instructions. The paths were updated from `../../../mcp-servers/openshift/README.md` to `../../../kubernetes/mcp-servers/openshift-mcp/README.md` and from `../../../mcp-servers/slack/README.md` to `../../../kubernetes/mcp-servers/slack-mcp/README.md`.
-   Updated the Tavily API key registration link from `https://tavily.com/home` to `https://app.tavily.com/home`.
-    Corrected the relative path for the "Getting Started" notebook link from `demos/rag_agentic/notebooks/Level0_getting_started_with_Llama_Stack.ipynb` to …

fix: fixed broken links in Notebook 5.

---

.env.example

This change make notebook 6 work in 1 click otherwise it throws an error in the last cell (followed the instructions command to create the .env: `cp .env.example .env`)
Ran all notebooks after making the change and they return the same output as before. Notebook 6 finishes without an error.

Update .env.example to set max tokens to 512

---

.env.example
demos/rag_agentic/notebooks/Level0_getting_started_with_Llama_Stack.ipynb

The PR adds two changes:
- Set REMOTE_BASE_URL="http://llamastack-server:8321/"   in the .env.example so that it's directly usable in the notebooks with the demo env llama stack server.
- Add a simple client.inference.chat_completion("Hi, how are you?") to notebook 0 to confirm that the client was able to connect to the LLS APIs.

Add UX improvements to notebook 0 and env vars

---

kubernetes/llama-stack/run.yaml

If the LLS server doesn't have the slack MCP server registered at runtime, then Level 5 and Level 6 notebooks will fail to run unless the user updates the Slack MCP URL in the env file.  OpenShift MCP server already comes pre-registered.
@cooktheryan I don't see a reason why this shouldn't work but I don't know an easy way to test this.

Add slack mcp server to run.yaml

---

Makefile

after running `make setup_local`, the tag for image `localhost/distribution-ollama` is `0.2.7`, not `0.2.6`. Leading to this error
```
Error: internal error: unable to copy from source docker://localhost/distribution-ollama:0.2.6: initializing source docker://localhost/distribution-ollama:0.2.6: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused
```
output after listing images
```
llama-stack-demos % podman images
REPOSITORY                                  TAG         IMAGE ID      CREATED             SIZE
localhost/distribution-ollama               0.2.7       aee055501a88  About a minute ago  1.49 GB
localhost/streamlit_client                  latest      d1a8e39c318e  47 minutes ago      1.61 GB
```

updated localhost/distribution-ollama tag from 0.2.6 to 0.2.7

---

local_setup_guide.md

Fixed the hostname from `localhost` to `host.containers.internal`. This ensures that the Streamlit_client, running inside a container, can correctly connect to the Llama Stack server, which is running in a separate container and exposed via the host network.

fixed client configuration endpoint command to use host machine's network
